services:
  form-shot:
    build: .
    container_name: form-shot
    environment:
      - LOG_LEVEL=info
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    volumes:
      - ./.env:/app/.env:ro
      - ./output:/app/output:rw
    networks:
      - form-shot-network
    # Add security options for Chrome to run in container
    security_opt:
      - seccomp:unconfined
    # Example usage:
    # docker compose run --rm form-shot analyze https://example.com/form --screenshot
    
networks:
  form-shot-network:
    driver: bridge